<p align="right"><a href="./C1_W2_Lab01_Python_Numpy_Vectorization_Soln.ipynb">English</a> | <strong>中文</strong></p>

# Optional Lab: Python、NumPy 与向量化（Vectorization）
简要介绍本课程用到的一些科学计算，特别是 NumPy 科学计算包及其在 Python 中的用法。

# 大纲
- [&nbsp;&nbsp;1.1 目标](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 有用的参考资料](#toc_40015_1.2)
- [2 Python 与 NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 向量 Vectors](#toc_40015_3)
- [&nbsp;&nbsp;3.1 概述](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy 数组](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 向量的创建](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 向量上的运算](#toc_40015_3.4)
- [4 矩阵 Matrices](#toc_40015_4)
- [&nbsp;&nbsp;4.1 概述](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy 数组](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 矩阵的创建](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 矩阵上的运算](#toc_40015_4.4)

In [2]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

<a name="toc_40015_1.1"></a>
## 1.1 目标
在本实验中，你将：
- 复习 Course 1 中用到的 NumPy 与 Python 特性

<a name="toc_40015_1.2"></a>
## 1.2 有用的参考资料
- NumPy 文档（含基础入门）：[NumPy.org](https://NumPy.org/doc/stable/)
- 一个较有挑战的主题：[NumPy 广播 Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)

<a name="toc_40015_2"></a>
# 2 Python 与 NumPy <a name='Python and NumPy'></a>
Python 是本课程使用的编程语言，它内置了一组数值类型和算术运算。NumPy 是一个库，扩展了 Python 的基础能力，加入了更丰富的数据集合——包括更多数值类型、向量、矩阵，以及许多矩阵函数。NumPy 与 Python 配合得相当无缝：Python 的算术运算符能作用于 NumPy 数据类型，许多 NumPy 函数也接受 Python 数据类型。

<a name="toc_40015_3"></a>
# 3 向量 Vectors
<a name="toc_40015_3.1"></a>
## 3.1 概述
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >本课程中用到的向量，是有序的数字数组。记号上，向量用小写粗体字母表示，如 $\mathbf{x}$。向量的元素都是同一类型——比如一个向量不会同时包含字符和数字。数组中元素的个数常称为 *维度（dimension）*，不过数学家可能更喜欢称 *秩（rank）*。图中的向量维度为 $n$。向量的元素可用下标（index）引用。数学场景里下标通常从 1 到 n；在计算机科学和本课程的实验里，下标通常从 0 到 n-1。记号上，单独引用向量的某个元素时用下标标明位置，例如向量 $\mathbf{x}$ 的第 $0$ 个元素是 $x_0$。注意此时 x 不是粗体。

<a name="toc_40015_3.2"></a>
## 3.2 NumPy 数组

NumPy 的基本数据结构是一个可索引的 n 维 *数组（array）*，元素类型相同（`dtype`）。这里你可能注意到 '维度' 一词被重载了：上面它指向量中元素的个数，而这里维度指数组下标（index）的个数。一维（1-D）数组只有一个下标。在 Course 1 中，我们用 NumPy 一维数组来表示向量。

 - 一维数组，shape 为 (n,)：n 个元素，下标从 [0] 到 [n-1]

<a name="toc_40015_3.3"></a>
## 3.3 向量的创建

NumPy 中创建数据的函数，第一个参数通常是对象的 shape。它可以是一个单值（对应一维结果），也可以是一个元组 (n,m,...)（指定结果的形状）。下面是用这些函数创建向量的例子。

In [6]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.96801947 0.64165558 0.65674342 0.05300469], a shape = (4,), a data type = float64


有些创建数据的函数不接受 shape 元组：

In [7]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.80137786 0.27106422 0.86825633 0.63702531], a shape = (4,), a data type = float64


也可以手动指定取值。

In [8]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


上面这些都创建了一个含四个元素的一维向量 `a`。`a.shape` 返回其维度信息，这里 a.shape = `(4,)`，表示一个含 4 个元素的一维数组。

<a name="toc_40015_3.4"></a>
## 3.4 向量上的运算
我们来探索一些向量运算。
<a name="toc_40015_3.4.1"></a>
### 3.4.1 索引（Indexing）
向量的元素可通过索引和切片访问。NumPy 提供了一整套非常完整的索引与切片能力，这里只探索课程所需的基础部分。更多细节参见 [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html)。
**索引（Indexing）** 指通过元素在数组中的位置来引用 *某个元素*。
**切片（Slicing）** 指根据下标从数组中取出 *一个子集* 的元素。
NumPy 下标从零开始，所以向量 $\mathbf{a}$ 的第 3 个元素是 `a[2]`。

In [9]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 切片（Slicing）
切片用一组三个值（`start:stop:step`）来生成一段下标；也可以只给出其中部分。用例子最容易说明：

In [10]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 单个向量的运算
有一些有用的运算是作用在单个向量上的。

In [11]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 向量与向量的逐元素运算
大多数 NumPy 的算术、逻辑和比较运算也适用于向量，它们都是逐元素（element-by-element）进行的。例如
$$ c_i = a_i + b_i $$

In [12]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


当然，要正确运算，两个向量必须大小相同：

In [14]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 标量与向量的运算
向量可以被标量 '缩放（scaled）'。标量就是一个数，它会乘以向量的每一个元素。

In [15]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 向量与向量的点积（dot product）
点积是线性代数和 NumPy 的核心，本课程会大量用到，应当充分理解。点积如下所示。

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800> 

点积把两个向量中的值逐元素相乘，然后把结果求和。
向量点积要求两个向量的维度相同。

下面我们自己实现一版点积：

**用 for 循环** 实现一个返回两向量点积的函数。给定输入 $a$ 和 $b$，函数返回：
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
假设 `a` 和 `b` 形状相同。

In [18]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [19]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


注意，点积应返回一个标量值。

我们用 `np.dot` 试同样的运算。

In [20]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


上面可以看到，一维情形下 `np.dot` 的结果与我们的实现一致。

<a name="toc_40015_3.4.7"></a>
### 3.4.7 对速度的需求：向量化 vs for 循环
我们用 NumPy 是因为它能提升速度和内存效率。下面来演示：

In [21]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 267.4744 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 9619.5147 ms 


可见，这个例子里向量化带来了很大的加速。这是因为 NumPy 更好地利用了底层硬件中的数据并行能力：GPU 和现代 CPU 实现了 SIMD（Single Instruction, Multiple Data，单指令多数据）流水线，允许多个运算并行发出。这在机器学习中至关重要，因为数据集往往非常大。

<a name="toc_12345_3.4.8"></a>
### 3.4.8 Course 1 中的向量-向量运算
向量-向量运算会在 Course 1 中频繁出现。原因如下：
- 后面我们的样本会存放在一个维度为 (m,n) 的数组 `X_train` 里。具体会结合上下文再讲，这里重要的是知道它是一个二维数组（矩阵，见下一节）。
- `w` 是一个 shape 为 (n,) 的一维向量。
- 我们通过遍历样本来做运算，用对 X 索引的方式取出每个样本单独处理，例如 `X[i]`。
- `X[i]` 返回一个 shape 为 (n,) 的一维向量。因此涉及 `X[i]` 的运算常常是向量-向量运算。

这段解释略长，但在做向量运算时，对齐并理解各操作数的 shape 很重要。

In [22]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 矩阵 Matrices

<a name="toc_40015_4.1"></a>
## 4.1 概述
矩阵是二维数组，元素类型相同。记号上，矩阵用大写粗体字母表示，如 $\mathbf{X}$。在本实验及其他实验中，`m` 常指行数，`n` 指列数。矩阵的元素可用二维下标引用。数学场景里下标通常从 1 到 n；在计算机科学和本课程实验里，下标从 0 到 n-1。
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> 通用矩阵记号：第 1 个下标是行，第 2 个是列 </figcaption>
<figure/>

<a name="toc_40015_4.2"></a>
## 4.2 NumPy 数组

NumPy 的基本数据结构是一个可索引的 n 维 *数组*，元素类型相同（`dtype`），前面已介绍过。矩阵有一个二维（2-D）下标 [m,n]。

在 Course 1 中，二维矩阵用来存放训练数据。训练数据是 $m$ 个样本、每个 $n$ 个特征，构成一个 (m,n) 数组。Course 1 不直接对矩阵做运算，而通常把一个样本取出为向量再对其运算。下面你将复习：
- 数据创建
- 切片与索引

<a name="toc_40015_4.3"></a>
## 4.3 矩阵的创建
创建一维向量的那些函数同样能创建二维或 n 维数组。下面是一些例子。

下面通过给出 shape 元组来得到二维结果。注意 NumPy 用方括号来表示每个维度；还要注意 NumPy 打印时每行占一行。

In [23]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


也可以手动指定数据。用与上面打印格式相匹配的额外方括号来指定维度。

In [24]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 矩阵上的运算
我们来探索一些矩阵运算。

<a name="toc_40015_4.4.1"></a>
### 4.4.1 索引（Indexing）

矩阵多了第二个下标，两个下标描述 [行, 列]。访问时既可以返回一个元素，也可以返回一整行/列。见下：

In [26]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


值得留意最后一个例子：只指定行来访问矩阵，会返回一个 *一维向量*。

**Reshape（重塑形状）**
上一个例子用 [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) 来调整数组形状。
`a = np.arange(6).reshape(-1, 2) `
这行代码先创建了一个含六个元素的 *一维向量*，再用 reshape 命令把它重塑成一个 *二维* 数组。它也可以写成：
`a = np.arange(6).reshape(3, 2) `
得到同样的 3 行 2 列数组。
参数 -1 告诉函数：根据数组大小和列数，自动推算行数。

<a name="toc_40015_4.4.2"></a>
### 4.4.2 切片（Slicing）
切片用一组三个值（`start:stop:step`）来生成一段下标；也可以只给出其中部分。用例子最容易说明：

In [27]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## 恭喜！
在本实验中，你掌握了 Course 1 所需的 Python 与 NumPy 特性。

In [28]:
print("FINISH!!!")

FINISH!!!
