<p align="right"><a href="./Python_Basics_with_Numpy.ipynb">English</a> | <strong>中文</strong></p>

#### Python 基础与 Numpy（Python Basics with Numpy，选做作业）

欢迎来到你的第一个作业。本练习带你对 Python 做一个简短的入门。即使你以前用过 Python，它也能帮你熟悉我们将会用到的那些函数。

**说明：**
- 你将使用 Python 3。
- 除非题目明确要求，否则请避免使用 for 循环和 while 循环。
- 写完你的函数后，运行紧跟其下的 cell，检查结果是否正确。

**完成本作业后，你将：**
- 会使用 iPython Notebooks
- 会使用 numpy 函数以及 numpy 的矩阵/向量运算
- 理解 "广播（broadcasting）" 的概念
- 会把代码向量化

我们开始吧！

## 关于提交给 AutoGrader 的重要提示

在把你的作业提交给 AutoGrader 之前，请确认你没有做以下这些事：

1. 你没有在作业里加任何 _额外的_ `print` 语句。
2. 你没有在作业里加任何 _额外的_ code cell。
3. 你没有更改任何函数参数。
4. 你没有在评分练习内部使用任何全局变量。除非题目特别要求，否则请避免这样做，改用局部变量。
5. 你没有在不需要改的地方更改作业代码，比如创建 _额外的_ 变量。

如果你做了上述任何一件事，提交作业时你会得到类似 `Grader Error: Grader feedback not found`（或其他类似意外）的错误。在寻求帮助/调试作业里的错误之前，请先检查这些。如果确实如此、而你又不记得自己改了什么，可以按这些[说明](https://www.coursera.org/learn/neural-networks-deep-learning/supplement/iLwon/h-ow-to-refresh-your-workspace)获取一份全新的作业副本。

## 目录
- [关于 iPython Notebooks](#0)
    - [练习 Exercise 1](#ex-1)
- [1 - 用 numpy 构建基础函数](#1)
    - [1.1 - sigmoid 函数, np.exp()](#1-1)
        - [练习 Exercise 2 - basic_sigmoid](#ex-2)
        - [练习 Exercise 3 - sigmoid](#ex-3)
    - [1.2 - Sigmoid 梯度](#1-2)
        - [练习 Exercise 4 - sigmoid_derivative](#ex-4)
    - [1.3 - 重塑数组（Reshaping arrays）](#1-3)
        - [练习 Exercise 5 - image2vector](#ex-5)
    - [1.4 - 对行做归一化](#1-4)
        - [练习 Exercise 6 - normalize_rows](#ex-6)
        - [练习 Exercise 7 - softmax](#ex-7)
- [2 - 向量化（Vectorization）](#2)
    - [2.1 实现 L1 和 L2 损失函数](#2-1)
        - [练习 Exercise 8 - L1](#ex-8)
        - [练习 Exercise 9 - L2](#ex-9)

<a name='0'></a>
## 关于 iPython Notebooks ##

iPython Notebooks 是嵌在网页里的交互式编程环境。本课程你会用到 iPython notebooks。你只需要在 # your code here 注释之间写代码。写完代码后，你可以按 "SHIFT"+"ENTER"、或点击 notebook 上方栏里的 "Run Cell"（用一个播放符号表示）来运行这个 cell。

我们常会在注释里写明 "(≈ X lines of code)"，告诉你大概需要写多少代码。这只是个粗略估计，所以如果你的代码更长或更短也不必在意。

In [1]:
### v1.2

<a name='ex-1'></a>
### 练习 Exercise 1
在下面的 cell 里把 test 设为 `"Hello World"` 以打印 "Hello World"，然后运行下面两个 cell。

In [2]:
# (≈ 1 line of code)
# test = 
# YOUR CODE STARTS HERE
test = "Hello World"
# YOUR CODE ENDS HERE

In [3]:
print ("test: " + test)

test: Hello World


**期望输出**：
test: Hello World

<font color='blue'>
<b>你需要记住的</b>：

- 用 SHIFT+ENTER（或 "Run cell"）运行你的 cell
- 只用 Python 3 在指定区域写代码
- 不要修改指定区域以外的代码

<a name='1'></a>
## 1 - 用 numpy 构建基础函数 ##

Numpy 是 Python 中科学计算的主要库，由一个庞大的社区维护（www.numpy.org）。在本练习中，你会学到几个关键的 numpy 函数，如 `np.exp`、`np.log` 和 `np.reshape`。你需要知道如何在后续作业里使用这些函数。

<a name='1-1'></a>
### 1.1 - sigmoid 函数, np.exp() ###

在用 `np.exp()` 之前，你会先用 `math.exp()` 来实现 sigmoid 函数。之后你就会明白为什么 `np.exp()` 比 `math.exp()` 更可取。

<a name='ex-2'></a>
### 练习 Exercise 2 - basic_sigmoid
构建一个函数，返回实数 x 的 sigmoid。用 `math.exp(x)` 作指数函数。

**提醒**：
$sigmoid(x) = \frac{1}{1+e^{-x}}$ 有时也称为 logistic 函数。它是一个非线性函数，不仅用于机器学习（逻辑回归 Logistic Regression），也用于深度学习。

<img src="images/Sigmoid.png" style="width:500px;height:228px;">

要引用某个特定库里的函数，你可以用 `package_name.function()` 来调用它。运行下面的代码，看一个用 `math.exp()` 的例子。

In [4]:
import math
from public_tests import *

# GRADED FUNCTION: basic_sigmoid

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    s = 1 / (1 + math.exp(-x))
    # YOUR CODE ENDS HERE
    
    return s

In [5]:
print("basic_sigmoid(1) = " + str(basic_sigmoid(1)))

basic_sigmoid_test(basic_sigmoid)

basic_sigmoid(1) = 0.7310585786300049
 All tests passed.


其实在深度学习里我们很少用 "math" 库，因为这些函数的输入是实数。而在深度学习里我们主要用矩阵和向量。这正是 numpy 更有用的原因。

In [6]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###

x = [1, 2, 3] # x becomes a python list object
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

TypeError: bad operand type for unary -: 'list'

事实上，如果 $ x = (x_1, x_2, ..., x_n)$ 是一个行向量，那么 `np.exp(x)` 会对 x 的每个元素施加指数函数。于是输出会是：`np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})`

In [7]:
import numpy as np

# example of np.exp
t_x = np.array([1, 2, 3])
print(np.exp(t_x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


此外，如果 x 是一个向量，那么像 $s = x + 3$ 或 $s = \frac{1}{x}$ 这样的 Python 运算，会输出一个与 x 同样大小的向量 s。

In [8]:
# example of vector operation
t_x = np.array([1, 2, 3])
print (t_x + 3)

[4 5 6]


任何时候你想了解某个 numpy 函数的更多信息，我们都鼓励你查阅[官方文档](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html)。

你也可以在 notebook 里新建一个 cell，写 `np.exp?`（例如）来快速查看文档。

<a name='ex-3'></a>
### 练习 Exercise 3 - sigmoid
用 numpy 实现 sigmoid 函数。

**说明**：x 现在既可以是实数，也可以是向量或矩阵。我们在 numpy 里用来表示这些形状（向量、矩阵……）的数据结构叫 numpy 数组（numpy arrays）。眼下你不需要知道更多。
$$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

In [9]:
# GRADED FUNCTION: sigmoid

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    s = 1 / (1 + np.exp(-x))
    # YOUR CODE ENDS HERE
    
    return s

In [10]:
t_x = np.array([1, 2, 3])
print("sigmoid(t_x) = " + str(sigmoid(t_x)))

sigmoid_test(sigmoid)

sigmoid(t_x) = [0.73105858 0.88079708 0.95257413]
 All tests passed.


<a name='1-2'></a>
### 1.2 - Sigmoid 梯度

正如你在课上看到的，你需要计算梯度，才能用反向传播（backpropagation）来优化损失函数。我们来写你的第一个梯度函数。

<a name='ex-4'></a>
### 练习 Exercise 4 - sigmoid_derivative
实现函数 sigmoid_grad()，计算 sigmoid 函数关于其输入 x 的梯度。公式是：

$$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$

你通常分两步来写这个函数：
1. 令 s 为 x 的 sigmoid。你的 sigmoid(x) 函数在这里可能有用。
2. 计算 $\sigma'(x) = s(1-s)$

In [11]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    #(≈ 2 lines of code)
    # s = 
    # ds = 
    # YOUR CODE STARTS HERE
    s = 1 / (1 + np.exp(-x))
    ds = s * (1 - s)
    # YOUR CODE ENDS HERE
    
    return ds

In [12]:
t_x = np.array([1, 2, 3])
print ("sigmoid_derivative(t_x) = " + str(sigmoid_derivative(t_x)))

sigmoid_derivative_test(sigmoid_derivative)

sigmoid_derivative(t_x) = [0.19661193 0.10499359 0.04517666]
 All tests passed.


<a name='1-3'></a>
### 1.3 - 重塑数组（Reshaping arrays）###

深度学习中两个常用的 numpy 函数是 [np.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) 和 [np.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)。
- X.shape 用来获取矩阵/向量 X 的形状（维度）。
- X.reshape(...) 用来把 X 重塑成别的维度。

例如，在计算机科学里，一张图像由形状为 $(length, height, depth = 3)$ 的三维数组表示。然而，当你把一张图像作为算法的输入读入时，你会把它转换成形状为 $(length*height*3, 1)$ 的向量。换句话说，你把这个三维数组 "展开（unroll）"、或者说重塑成一个一维向量。

<img src="images/image2vector_kiank.png" style="width:500px;height:300;">

<a name='ex-5'></a>
### 练习 Exercise 5 - image2vector
实现 `image2vector()`，它接收一个形状为 (length, height, 3) 的输入，返回一个形状为 (length\*height\*3, 1) 的向量。例如，若你想把形状为 (a, b, c) 的数组 v 重塑成形状为 (a*b,c) 的向量，你会这样做：
``` python
v = v.reshape((v.shape[0] * v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c
```
- 请不要把图像的维度硬编码成常数。而应该用 `image.shape[0]` 等来查出你需要的量。
- 你可以用 v = v.reshape(-1, 1)。只要确保你理解它为什么能行。

In [13]:
# GRADED FUNCTION:image2vector

def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    # (≈ 1 line of code)
    # v =
    # YOUR CODE STARTS HERE
    v = image.reshape((image.shape[0] * image.shape[1] * image.shape[2],1))
    # YOUR CODE ENDS HERE
    
    return v

In [14]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(t_image)))

image2vector_test(image2vector)


image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
 All tests passed.


<a name='1-4'></a>
### 1.4 - 对行做归一化

我们在机器学习和深度学习里用的另一个常见技巧是对数据做归一化（normalize）。它常能带来更好的性能，因为归一化后梯度下降收敛更快。这里所说的归一化，是指把 x 变成 $ \frac{x}{\| x\|} $（把 x 的每个行向量除以它的范数）。

例如，若
$$x = \begin{bmatrix}
        0 & 3 & 4 \\
        2 & 6 & 4 \\
\end{bmatrix}\tag{3}$$
则
$$\| x\| = \text{np.linalg.norm(x, axis=1, keepdims=True)} = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4} $$
以及
$$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}$$

注意，你可以把大小不同的矩阵相除，并且能正常工作：这叫广播（broadcasting），你会在第 5 部分学到它。

用 `keepdims=True` 时，结果会正确地与原始 x 广播。

`axis=1` 意味着你会按行（row-wise）求范数。如果你需要按列（column-wise）求范数，就得设 `axis=0`。

numpy.linalg.norm 还有一个参数 `ord`，我们在其中指定要做的归一化类型（下面的练习里你会做 2-范数）。要熟悉各种归一化类型，你可以访问 [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

<a name='ex-6'></a>
### 练习 Exercise 6 - normalize_rows
实现 normalizeRows()，对一个矩阵的各行做归一化。把这个函数作用到输入矩阵 x 后，x 的每一行都应是一个单位长度（即长度为 1）的向量。

In [17]:
# GRADED FUNCTION: normalize_rows

def normalize_rows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    # x_norm =
    # Divide x by its norm.
    # x =
    # YOUR CODE STARTS HERE
    x_norm = np.linalg.norm(x,ord = 2,axis = 1,keepdims = True)
    # Divide x by its norm.
    x = x / x_norm
    # YOUR CODE ENDS HERE

    return x

In [18]:
x = np.array([[0., 3., 4.],
              [1., 6., 4.]])
print("normalizeRows(x) = " + str(normalize_rows(x)))

normalizeRows_test(normalize_rows)

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
 All tests passed.


**注意**：
在 normalize_rows() 里，你可以试着打印 x_norm 和 x 的形状，然后重跑评估。你会发现它们形状不同。这是正常的，因为 x_norm 取的是 x 每一行的范数。所以 x_norm 的行数相同，但只有 1 列。那么当你把 x 除以 x_norm 时是怎么成功的呢？这叫广播（broadcasting），我们现在就来讲它！

<a name='ex-7'></a>
### 练习 Exercise 7 - softmax
用 numpy 实现一个 softmax 函数。你可以把 softmax 看作一个归一化函数，当你的算法需要对两个或更多类别做分类时会用到它。你会在本专项的第二门课里学到更多关于 softmax 的内容。

**说明**：
- $\text{for } x \in \mathbb{R}^{1\times n} \text{,     }$

\begin{align*}
 softmax(x) &= softmax\left(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n
\end{bmatrix}\right) \\&= \begin{bmatrix}
    \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}}
\end{bmatrix}
\end{align*}

- $\text{for a matrix } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ maps to the element in the $i^{th}$ row and $j^{th}$ column of $x$, thus we have: }$

\begin{align*}
softmax(x) &= softmax\begin{bmatrix}
            x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
            x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
            \vdots & \vdots & \vdots & \ddots & \vdots \\
            x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
            \end{bmatrix} \\ \\&=
 \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} \\ \\ &= \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    \vdots  \\
    softmax\text{(last row of x)} \\
\end{pmatrix}
\end{align*}

**注意：**
注意，在本课程后面，你会看到用 "m" 表示 "训练样本的数量"，且每个训练样本占矩阵里的一列。此外，每个特征占单独一行（同一行里是同一个特征的数据）。
softmax 应对每个训练样本的所有特征来做，所以 softmax 会在列上进行（等到本课程后面切换到那种表示方式时）。

不过，在本次编程练习里，我们只是专注于熟悉 Python，所以我们用常见的数学记号 $m \times n$，
其中 $m$ 是行数、$n$ 是列数。

In [19]:
# GRADED FUNCTION: softmax

def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (m,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    
    #(≈ 3 lines of code)
    # Apply exp() element-wise to x. Use np.exp(...).
    # x_exp = ...

    # Create a vector x_sum that sums each row of x_exp. Use np.sum(..., axis = 1, keepdims = True).
    # x_sum = ...
    
    # Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
    # s = ...
    
    # YOUR CODE STARTS HERE
    # Apply exp() element-wise to x. Use np.exp(...).
    x_exp = np.exp(x)

    # Create a vector x_sum that sums each row of x_exp. Use np.sum(..., axis = 1, keepdims = True).
    x_sum = np.sum(x_exp,axis = 1,keepdims = True)
    
    # Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
    s = x_exp / x_sum
    
    # YOUR CODE ENDS HERE
    
    return s

In [20]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(t_x)))

softmax_test(softmax)

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
 All tests passed.


#### 说明
- 如果你打印上面 x_exp、x_sum 和 s 的形状并重跑评估 cell，你会看到 x_sum 的形状是 (2,1)，而 x_exp 和 s 的形状是 (2,5)。**x_exp/x_sum** 之所以能成，靠的是 python 广播。

恭喜！你现在对 python numpy 已经有了相当好的理解，并实现了几个在深度学习中会用到的实用函数。

<font color='blue'>
<b>你需要记住的：</b>

- np.exp(x) 对任意 np.array x 都有效，会对每个坐标施加指数函数
- sigmoid 函数及其梯度
- image2vector 在深度学习中很常用
- np.reshape 被广泛使用。将来你会发现，把矩阵/向量的维度理清楚，能帮你消除大量 bug。
- numpy 有高效的内置函数
- 广播（broadcasting）极其有用

<a name='2'></a>
## 2 - 向量化（Vectorization）


在深度学习里，你要处理非常大的数据集。因此，一个计算上非最优的函数会成为算法里的巨大瓶颈，导致模型运行起来慢得要命。为确保你的代码计算高效，你会用到向量化（vectorization）。例如，试着分辨下面这几种点积/外积/逐元素积实现之间的差别。

In [21]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we create a len(x1)*len(x2) matrix with only zeros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.19275399999996168ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [22]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.45683800000007047ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.25485599999997ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.07157000000002078ms
gdot = [15.64064228 11.0655343  11.80313152]

你可能已经注意到，向量化实现干净、也更高效得多。对更大的向量/矩阵，运行时间的差距会变得更大。

**注意** `np.dot()` 执行的是矩阵-矩阵或矩阵-向量乘法。这不同于 `np.multiply()` 和 `*` 运算符（后者等价于 Matlab/Octave 里的 `.*`），它们执行的是逐元素乘法。

<a name='2-1'></a>
### 2.1 实现 L1 和 L2 损失函数

<a name='ex-8'></a>
### 练习 Exercise 8 - L1
实现 L1 损失的 numpy 向量化版本。你可能会发现函数 abs(x)（x 的绝对值）有用。

**提醒**：
- 损失（loss）用来评估你模型的表现。损失越大，你的预测（$ \hat{y} $）与真实值（$y$）差得越远。在深度学习里，你会用像梯度下降这样的优化算法来训练模型、最小化代价。
- L1 损失定义为：
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^{m-1}|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$

In [27]:
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    #(≈ 1 line of code)
    # loss = 
    # YOUR CODE STARTS HERE
    loss = np.sum(np.abs(yhat-y),axis = 0)
    # YOUR CODE ENDS HERE
    
    return loss

In [28]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat, y)))

L1_test(L1)

L1 = 1.1
 All tests passed.


<a name='ex-9'></a>
### 练习 Exercise 9 - L2
实现 L2 损失的 numpy 向量化版本。实现 L2 损失有好几种方法，但你可能会发现函数 np.dot() 有用。提醒一下，若 $x = [x_1, x_2, ..., x_n]$，则 `np.dot(x,x)` = $\sum_{j=1}^n x_j^{2}$。

- L2 损失定义为 $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [29]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    #(≈ 1 line of code)
    # loss = ...
    # YOUR CODE STARTS HERE
    loss = np.dot(np.abs(yhat-y),np.abs(yhat-y))
    # YOUR CODE ENDS HERE
    
    return loss

In [30]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))

L2_test(L2)

L2 = 0.43
 All tests passed.


恭喜你完成这个作业。我们希望这个小小的热身练习能帮到你未来的作业，那些作业会更激动人心、更有意思！

<font color='blue'>
<b>要记住的：</b>

- 向量化在深度学习里非常重要。它带来计算效率和清晰度。
- 你复习了 L1 和 L2 损失。
- 你熟悉了许多 numpy 函数，如 np.sum、np.dot、np.multiply、np.maximum 等……